// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'firebase_options.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-fLKTlhQ1FUlrbmEsjBosNUCUypS_5G8',
    appId: '1:271810739793:web:f095bbb911556eb6d44270',
    messagingSenderId: '271810739793',
    projectId: 'attendance-go',
    authDomain: 'attendance-go.firebaseapp.com',
    storageBucket: 'attendance-go.appspot.com',
    measurementId: 'G-XGYEJMLCH1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrNTv8Vcj4nTPz4kYewRlpfAIbYo8GX_8',
    appId: '1:271810739793:android:3910740a3b53c459d44270',
    messagingSenderId: '271810739793',
    projectId: 'attendance-go',
    storageBucket: 'attendance-go.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdthcXJFJjNL-LKCiZAvmZpxiTpwnuk6U',
    appId: '1:271810739793:ios:e61c5c0d7daa8eced44270',
    messagingSenderId: '271810739793',
    projectId: 'attendance-go',
    storageBucket: 'attendance-go.appspot.com',
    iosBundleId: 'com.example.attedance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdthcXJFJjNL-LKCiZAvmZpxiTpwnuk6U',
    appId: '1:271810739793:ios:fb2ea5c391e262c3d44270',
    messagingSenderId: '271810739793',
    projectId: 'attendance-go',
    storageBucket: 'attendance-go.appspot.com',
    iosBundleId: 'com.example.attedance.RunnerTests',
  );
}
